https://github.com/nymta/Open-Data-Week-2024/blob/main/subway_hourly_ridership_soql_analysis.ipynb

In [20]:
import pandas as pd
from io import StringIO

In [21]:
def establish_nys_session():
    session = requests.Session()
    # Add headers or authentication if needed
    return session

url = """https://data.ny.gov/resource/wujg-7c2s.csv?$query=
SELECT 
    station_complex,
    round(SUM(ridership),0) AS total_ridership
WHERE 
    transit_timestamp >= '2023-12-31T00:00:00' 
    AND 
    transit_timestamp <= '2024-01-01T00:00:00'
GROUP BY 
    station_complex
ORDER BY 
    station_complex
"""

In [135]:
url = """https://data.ny.gov/resource/wujg-7c2s.csv?$limit=1000000000&$where=transit_timestamp >= '2023-12-31T00:00:00' AND transit_timestamp <= '2024-01-01T00:00:00' AND borough = 'Manhattan' AND station_complex='Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)'&$order=transit_timestamp ASC&$group=station_complex, transit_timestamp&$select=station_complex, transit_timestamp, round(SUM(ridership),0) as total_ridership """
url = """https://data.ny.gov/resource/wujg-7c2s.csv?$limit=1000000000&$where=station_complex='Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)'"""


url = """https://data.ny.gov/resource/wujg-7c2s.csv?$query=SELECT
    date_trunc_y(transit_timestamp) AS year,
    station_complex,
    round(SUM(ridership),0) AS total_ridership
WHERE
    station_complex = 'Vernon Blvd-Jackson Av (7)' AND
    (
        (transit_timestamp >= '2022-07-04T00:00:00' AND transit_timestamp <= '2022-07-04T23:59:59') OR
        (transit_timestamp >= '2023-07-04T00:00:00' AND transit_timestamp <= '2023-07-04T23:59:59')
    )
GROUP BY
    year, station_complex
ORDER BY
    year ASC
"""

url = """https://data.ny.gov/resource/wujg-7c2s.csv?$query=
SELECT 
    station_complex,
    Georeference,
    round(SUM(ridership),0) AS total_ridership
WHERE 
    transit_timestamp >= '2023-12-31T00:00:00' 
    AND 
    transit_timestamp <= '2024-01-01T00:00:00'
GROUP BY 
    station_complex, Georeference
ORDER BY 
    station_complex
"""

session = establish_nys_session()
response = session.get(url)


# Convert the CSV response to a DataFrame
data = StringIO(response.text)

print(data)

df = pd.read_csv(data, header=0)

df

<_io.StringIO object at 0x147901310>

             station_complex                  Georeference  total_ridership
0                 103 St (1)  POINT (-73.968376 40.799446)             6150
1                 103 St (6)     POINT (-73.94748 40.7906)             3676
2               103 St (C,B)   POINT (-73.96146 40.796093)             2142
3    103 St-Corona Plaza (7)    POINT (-73.8627 40.749866)            10375
4                 104 St (A)   POINT (-73.837685 40.68171)              417
..                       ...                           ...              ...
478     Woodhaven Blvd (M,R)   POINT (-73.86923 40.733105)             6912
479             Woodlawn (4)   POINT (-73.87875 40.886036)             1624
480        WTC Cortlandt (1)   POINT (-74.01219 40.711834)            13680
481              York St (F)   POINT (-73.98675 40.701397)             8179
482            Zerega Av (6)   POINT (-73.84704 40.836487)              614

[483 rows x 3 columns]